sudo: false
language: python
python:
    - 3.4
    - 3.5
    - 3.6
install:
    # Old versions of pip can't handle extras_require in setup.py.
    - pip install --upgrade pip
    - pip install .[dev]
script:
    - make all
cache: pip
